### PR TITLE
Bugfix: fix cmake ENABLE_TESTS flag (make disabling of IE tests compilation possible)

### PR DESCRIPTION
**Pull request by banderlog**
Save compilation time -- add an option to not make all IE tests.

### CODE REVIEW

**Comment by banderlog** [comment]
Well, of course I've checked it. I am aware of existence of `dldt` documentation and `dldt/inference-engine/cmake/features.cmake` file. I even read it before proposing commit here :)

But, if I run cmake with this flags:
```bash
cmake -D CMAKE_BUILD_TYPE=Release \
    -D THREADING=TBB \
    -D GEMM=JIT \
    -D ENABLE_MKL_DNN=ON \
    -D ENABLE_OPENCV=OFF \
    -D BUILD_SHARED_LIBS=OFF \
    -D BUILD_TESTS=OFF \
    -D ENABLE_PLUGIN_RPATH=OFF \
    -D ENABLE_PYTHON=OFF \
    -D ENABLE_TESTS=OFF \
    -D ENABLE_SAMPLES=OFF \
    -D ENABLE_STRESS_UNIT_TESTS=OFF \
    -D ENABLE_GAPI_TESTS=OFF \
    -D GAPI_TEST_PERF=OFF \
    -D ENABLE_SEGMENTATION_TESTS=OFF \
    -D ENABLE_OBJECT_DETECTION_TESTS=OFF \
    -D ENABLE_GNA=OFF \
    -D ENABLE_PROFILING_ITT=OFF \
    -D ENABLE_ALTERNATIVE_TEMP=OFF \
    -D ENABLE_CLDNN=OFF ..
```

I still have `tests/unit/CMakeFiles/InferenceEngineUnitTests.dir/*` compiled and nice 33MB `/dldt/inference-engine/bin/intel64/Release/InferenceEngineUnitTests` binary file.

`ENABLE_TESTS` flag mentioned only in two files -- `inference-engine/cmake/check_features.cmake` and `inference-engine/cmake/features.cmake` and it hasn't any conditions to include\exclude test subdir there. 

I assumed that it does something else, thus I added `DISABLE_IE_TESTS` flag. Now I'm thinking that I've found a bug, and `ENABLE_TESTS`  does not work at all, in that case I could just switch flag name in my patch. But I am not sure that I am right in my suggestions. Please tell me if it so.

**Comment by alalek** [comment]
@banderlog Hi,

I believe, main purpose of the comment above is to avoid creation of option under a new name `DISABLE_IE_TESTS`.
Lets try to reuse existed one ([ENABLE_TESTS](https://github.com/opencv/dldt/blob/2019_R1.0.1/inference-engine/cmake/features.cmake#L65)).

```
if(ENABLE_TESTS)
    add_subdirectory(tests)
endif()
```

**Comment by banderlog** [comment]
@dkurt sorry for my misunderstanding, I did not mean to be rude

**Comment by banderlog** [comment]
Should I make any other movements or just wait?

**Comment by dkurt** [comment]
@asuhov, please take a look.

**Comment by banderlog** [comment]
Guys? 2019_R1.1 still has that bug.

**Pull request closed without merging**
