### PR TITLE
Bugfix: fix cmake ENABLE_TESTS flag

### PR DESCRIPTION
**Pull request by banderlog**
Save compilation time -- fix an option to not make all IE tests.

#139

### CODE REVIEW

**Comment by dkurt** [comment]
@banderlog, Please do not reopen PRs (https://github.com/opencv/dldt/pull/139).

**Comment by banderlog** [comment]
My bad, thought that is a good idea to update it for latest version of `CMakeLists.txt`.

**Comment by alalek** [comment]
> to update it for latest version

No needs to re-open PR, apply changes "inplace":

1. Use `git rebase -i upstream/<target_branch>`, where
    - `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`)
    - `<target_branch>` is `2019` for this PR

2. Push rebased commits into source branch (`patch-2`) of your fork (with `--force` option).

**Comment by banderlog** [comment]
something went wrong

```bash
git clone https://github.com/banderlog/dldt
cd dldt
git remote add upstream https://github.com/opencv/dldt
git fetch upstream
git rebase -i upstream/2019
git push origin 2019:patch-2 --force
```

**Comment by alalek** [comment]
Commits from your source branch in the GitHub fork has been removed.

> banderlog force-pushed the banderlog:patch-2  branch from 0064f52 to 693ab4e 5 hours ago

This line is wrong:
```.diff
-git push origin 2019:patch-2 --force
+git push origin patch-2 --force
```
(you pushed code from you local "2019" branch (without any new commits) into your "patch-2" in GitHub fork)

Try the right command and reopen PR (if GitHub allows that)

**Comment by banderlog** [comment]
@alalek you totally right, thank you for explanation

Now it looks like it was supposed to be.

`git push origin origin:patch-2`

**Comment by tdp2110** [comment]
@banderlog how's your progress on this?
I find this change useful too, and will use a fork of the repo until this is resolved.

**Comment by banderlog** [comment]
@tdp2110 thank you for supporting. As far as I concerned, the next move is for developers, they must approve or reject this patch. Alas, all open source projects have a big lag between proposing and reviewing and, probably, they have more critical problems to attend to.

**Comment by banderlog** [comment]
And they fixed it without my patch.

**Comment by dkurt** [comment]
@banderlog, Current approach is to move GitHub branches to private repo, test and merge them and then add to release push. So that means this is your patch :) Sorry for inconvenience.

**Comment by dkurt** [comment]
@banderlog, BTW, https://github.com/opencv/open_model_zoo/ is now moved from this strategy to open source development. Do you mind if I ask you to propose your [python demo](https://github.com/opencv/open_model_zoo/pull/36) one more time to [develop](https://github.com/opencv/open_model_zoo/tree/develop) branch?

**Comment by banderlog** [comment]
@dkurt What a pity, I hoped for a dldt 'Contributor' bage that would look nicely in CV :disappointed:.

>Do you mind if I ask you to propose your python demo one more time to develop branch?

It was applied in 2018 but somehow not in 2019? :) I will check if it still works and propose a merge request.

**Pull request closed without merging**
